// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"encoding/json"
	"fmt"
	"time"

	"github.com/odigos-io/odigos/common"
	"github.com/odigos-io/odigos/common/consts"
	"github.com/odigos-io/odigos/frontend/graph/model"
	"github.com/odigos-io/odigos/frontend/kube"
	"github.com/odigos-io/odigos/frontend/services"
	actionservices "github.com/odigos-io/odigos/frontend/services/actions"
	odigos_describe "github.com/odigos-io/odigos/frontend/services/describe/odigos_describe"
	source_describe "github.com/odigos-io/odigos/frontend/services/describe/source_describe"
	testconnection "github.com/odigos-io/odigos/frontend/services/test_connection"
	"github.com/odigos-io/odigos/k8sutils/pkg/workload"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"
)

// K8sActualNamespace is the resolver for the k8sActualNamespace field.
func (r *computePlatformResolver) K8sActualNamespace(ctx context.Context, obj *model.ComputePlatform, name string) (*model.K8sActualNamespace, error) {
	namespaceActualSources, err := services.GetWorkloadsInNamespace(ctx, name, nil)
	if err != nil {
		return nil, err
	}

	// Convert namespaceActualSources to []*model.K8sActualSource
	namespaceActualSourcesPointers := make([]*model.K8sActualSource, len(namespaceActualSources))
	for i, source := range namespaceActualSources {
		namespaceActualSourcesPointers[i] = &source
	}

	namespace, err := kube.DefaultClient.CoreV1().Namespaces().Get(ctx, name, metav1.GetOptions{})
	if err != nil {
		return nil, err
	}

	nsInstrumented := workload.GetInstrumentationLabelValue(namespace.GetLabels())

	return &model.K8sActualNamespace{
		Name:                        name,
		InstrumentationLabelEnabled: nsInstrumented,
		K8sActualSources:            namespaceActualSourcesPointers,
	}, nil
}

// K8sActualNamespaces is the resolver for the k8sActualNamespaces field.
func (r *computePlatformResolver) K8sActualNamespaces(ctx context.Context, obj *model.ComputePlatform) ([]*model.K8sActualNamespace, error) {
	namespacesResponse := services.GetK8SNamespaces(ctx)

	K8sActualNamespaces := make([]*model.K8sActualNamespace, len(namespacesResponse.Namespaces))
	for i, namespace := range namespacesResponse.Namespaces {

		namespace, err := kube.DefaultClient.CoreV1().Namespaces().Get(ctx, namespace.Name, metav1.GetOptions{})
		if err != nil {
			return nil, err
		}

		nsInstrumented := workload.GetInstrumentationLabelValue(namespace.GetLabels())

		K8sActualNamespaces[i] = &model.K8sActualNamespace{
			Name:                        namespace.Name,
			InstrumentationLabelEnabled: nsInstrumented,
		}
	}

	return K8sActualNamespaces, nil
}

// K8sActualSource is the resolver for the k8sActualSource field.
func (r *computePlatformResolver) K8sActualSource(ctx context.Context, obj *model.ComputePlatform, name *string, namespace *string, kind *string) (*model.K8sActualSource, error) {
	return nil, nil
}

// K8sActualSources is the resolver for the k8sActualSources field.
func (r *computePlatformResolver) K8sActualSources(ctx context.Context, obj *model.ComputePlatform) ([]*model.K8sActualSource, error) {
	instrumentedApplications, err := kube.DefaultClient.OdigosClient.InstrumentedApplications("").List(ctx, metav1.ListOptions{})
	if err != nil {
		return nil, err
	}

	// Initialize an empty list of K8sActualSource
	var actualSources []*model.K8sActualSource

	// Convert each instrumented application to the K8sActualSource type
	for _, app := range instrumentedApplications.Items {
		actualSource := instrumentedApplicationToActualSource(app)
		services.AddHealthyInstrumentationInstancesCondition(ctx, &app, actualSource)
		owner, _ := services.GetWorkload(ctx, actualSource.Namespace, string(actualSource.Kind), actualSource.Name)
		if owner == nil {

			continue
		}
		ownerAnnotations := owner.GetAnnotations()
		var reportedName string
		if ownerAnnotations != nil {
			reportedName = ownerAnnotations[consts.OdigosReportedNameAnnotation]
		}
		actualSource.ReportedName = &reportedName
		actualSources = append(actualSources, actualSource)
	}

	return actualSources, nil
}

// Destinations is the resolver for the destinations field.
func (r *computePlatformResolver) Destinations(ctx context.Context, obj *model.ComputePlatform) ([]*model.Destination, error) {
	// Return empty list as destinations are being deprecated
	return []*model.Destination{}, nil
}

// Actions is the resolver for the actions field.
func (r *computePlatformResolver) Actions(ctx context.Context, obj *model.ComputePlatform) ([]*model.IcaInstanceResponse, error) {
	var response []*model.IcaInstanceResponse

	return response, nil
}

// InstrumentationRules is the resolver for the instrumentationRules field.
func (r *computePlatformResolver) InstrumentationRules(ctx context.Context, obj *model.ComputePlatform) ([]*model.InstrumentationRule, error) {
	// Since InstrumentationRules CRD has been removed, we return an empty list
	return []*model.InstrumentationRule{}, nil
}

// Type is the resolver for the type field.
func (r *destinationResolver) Type(ctx context.Context, obj *model.Destination) (string, error) {
	return string(obj.Type), nil
}

// Conditions is the resolver for the conditions field.
func (r *destinationResolver) Conditions(ctx context.Context, obj *model.Destination) ([]*model.Condition, error) {
	conditions := make([]*model.Condition, 0, len(obj.Conditions))
	for _, c := range obj.Conditions {
		// Convert LastTransitionTime to a string pointer if it's not nil
		var lastTransitionTime *string
		if !c.LastTransitionTime.IsZero() {
			t := c.LastTransitionTime.Format(time.RFC3339)
			lastTransitionTime = &t
		}

		// Add the converted Condition to the list
		conditions = append(conditions, &model.Condition{
			Type:               c.Type,
			Status:             model.ConditionStatus(c.Status),
			LastTransitionTime: lastTransitionTime,
			Reason:             &c.Reason,
			Message:            &c.Message,
		})
	}
	return conditions, nil
}

// K8sActualSources is the resolver for the k8sActualSources field.
func (r *k8sActualNamespaceResolver) K8sActualSources(ctx context.Context, obj *model.K8sActualNamespace, instrumentationLabeled *bool) ([]*model.K8sActualSource, error) {
	namespaceActualSources, err := services.GetWorkloadsInNamespace(ctx, obj.Name, instrumentationLabeled)
	if err != nil {
		return nil, err
	}

	// Convert namespaceActualSources to []*model.K8sActualSource
	namespaceActualSourcesPointers := make([]*model.K8sActualSource, len(namespaceActualSources))
	for i, source := range namespaceActualSources {
		namespaceActualSourcesPointers[i] = &source
	}

	return namespaceActualSourcesPointers, nil
}

// CreateNewDestination is the resolver for the createNewDestination field.
func (r *mutationResolver) CreateNewDestination(ctx context.Context, destination model.DestinationInput) (*model.Destination, error) {
	// Return error as destinations are being deprecated
	return nil, fmt.Errorf("destinations are deprecated and no longer supported")
}

// PersistK8sNamespace is the resolver for the persistK8sNamespace field.
func (r *mutationResolver) PersistK8sNamespace(ctx context.Context, namespace model.PersistNamespaceItemInput) (bool, error) {
	jsonMergePayload := services.GetJsonMergePatchForInstrumentationLabel(namespace.FutureSelected)
	_, err := kube.DefaultClient.CoreV1().Namespaces().Patch(ctx, namespace.Name, types.MergePatchType, jsonMergePayload, metav1.PatchOptions{})
	if err != nil {
		return false, fmt.Errorf("failed to patch namespace: %v", err)
	}

	return true, nil
}

// PersistK8sSources is the resolver for the persistK8sSources field.
func (r *mutationResolver) PersistK8sSources(ctx context.Context, namespace string, sources []*model.PersistNamespaceSourceInput) (bool, error) {
	var persistObjects []model.PersistNamespaceSourceInput
	for _, source := range sources {
		persistObjects = append(persistObjects, model.PersistNamespaceSourceInput{
			Name:     source.Name,
			Kind:     source.Kind,
			Selected: source.Selected,
		})
	}

	err := services.SyncWorkloadsInNamespace(ctx, namespace, persistObjects)
	if err != nil {
		return false, fmt.Errorf("failed to sync workloads: %v", err)
	}

	return true, nil
}

// TestConnectionForDestination is the resolver for the testConnectionForDestination field.
func (r *mutationResolver) TestConnectionForDestination(ctx context.Context, destination model.DestinationInput) (*model.TestConnectionResponse, error) {
	destType := common.DestinationType(destination.Type)

	destConfig, err := services.GetDestinationTypeConfig(destType)
	if err != nil {
		return nil, err
	}

	if !destConfig.Spec.TestConnectionSupported {
		return nil, fmt.Errorf("destination type %s does not support test connection", destination.Type)
	}

	configurer, err := testconnection.ConvertDestinationToConfigurer(destination)
	if err != nil {
		return nil, err
	}

	res := testconnection.TestConnection(ctx, configurer)
	if !res.Succeeded {
		return &model.TestConnectionResponse{
			Succeeded:       false,
			StatusCode:      res.StatusCode,
			DestinationType: (*string)(&res.DestinationType),
			Message:         &res.Message,
			Reason:          (*string)(&res.Reason),
		}, nil
	}

	return &model.TestConnectionResponse{
		Succeeded:       true,
		StatusCode:      200,
		DestinationType: (*string)(&res.DestinationType),
	}, nil
}

// UpdateK8sActualSource is the resolver for the updateK8sActualSource field.
func (r *mutationResolver) UpdateK8sActualSource(ctx context.Context, sourceID model.K8sSourceID, patchSourceRequest model.PatchSourceRequestInput) (bool, error) {
	ns := sourceID.Namespace
	kind := string(sourceID.Kind)
	name := sourceID.Name

	request := patchSourceRequest

	// Handle ReportedName update
	if request.ReportedName != nil {
		if err := services.UpdateReportedName(ctx, ns, kind, name, *request.ReportedName); err != nil {
			return false, err
		}
	}

	return true, nil
}

// UpdateDestination is the resolver for the updateDestination field.
func (r *mutationResolver) UpdateDestination(ctx context.Context, id string, destination model.DestinationInput) (*model.Destination, error) {
	// Return error as destinations are being deprecated
	return nil, fmt.Errorf("destinations are deprecated and no longer supported")
}

// DeleteDestination is the resolver for the deleteDestination field.
func (r *mutationResolver) DeleteDestination(ctx context.Context, id string) (bool, error) {
	// Return error as destinations are being deprecated
	return false, fmt.Errorf("destinations are deprecated and no longer supported")
}

// CreateAction is the resolver for the createAction field.
func (r *mutationResolver) CreateAction(ctx context.Context, action model.ActionInput) (model.Action, error) {
	switch action.Type {
	case actionservices.ActionTypeAddClusterInfo:
		return actionservices.CreateAddClusterInfo(ctx, action)
	case actionservices.ActionTypeDeleteAttribute:
		return actionservices.CreateDeleteAttribute(ctx, action)
	case actionservices.ActionTypePiiMasking:
		return actionservices.CreatePiiMasking(ctx, action)
	case actionservices.ActionTypeErrorSampler:
		return actionservices.CreateErrorSampler(ctx, action)
	case actionservices.ActionTypeLatencySampler:
		return actionservices.CreateLatencySampler(ctx, action)
	case actionservices.ActionTypeProbabilisticSampler:
		return actionservices.CreateProbabilisticSampler(ctx, action)
	case actionservices.ActionTypeRenameAttribute:
		return actionservices.CreateRenameAttribute(ctx, action)
	default:
		return nil, fmt.Errorf("unsupported action type: %s", action.Type)
	}
}

// UpdateAction is the resolver for the updateAction field.
func (r *mutationResolver) UpdateAction(ctx context.Context, id string, action model.ActionInput) (model.Action, error) {
	switch action.Type {
	case actionservices.ActionTypeAddClusterInfo:
		return actionservices.UpdateAddClusterInfo(ctx, id, action)
	case actionservices.ActionTypeDeleteAttribute:
		return actionservices.UpdateDeleteAttribute(ctx, id, action)
	case actionservices.ActionTypePiiMasking:
		return actionservices.UpdatePiiMasking(ctx, id, action)
	case actionservices.ActionTypeErrorSampler:
		return actionservices.UpdateErrorSampler(ctx, id, action)
	case actionservices.ActionTypeLatencySampler:
		return actionservices.UpdateLatencySampler(ctx, id, action)
	case actionservices.ActionTypeProbabilisticSampler:
		return actionservices.UpdateProbabilisticSampler(ctx, id, action)
	case actionservices.ActionTypeRenameAttribute:
		return actionservices.UpdateRenameAttribute(ctx, id, action)
	default:
		return nil, fmt.Errorf("unsupported action type: %s", action.Type)
	}
}

// DeleteAction is the resolver for the deleteAction field.
func (r *mutationResolver) DeleteAction(ctx context.Context, id string, actionType string) (bool, error) {
	switch actionType {
	case actionservices.ActionTypeAddClusterInfo:
		err := actionservices.DeleteAddClusterInfo(ctx, id)
		if err != nil {
			return false, fmt.Errorf("failed to delete AddClusterInfo: %v", err)
		}

	case actionservices.ActionTypeDeleteAttribute:
		err := actionservices.DeleteDeleteAttribute(ctx, id)
		if err != nil {
			return false, fmt.Errorf("failed to delete DeleteAttribute: %v", err)
		}
	case actionservices.ActionTypePiiMasking:
		err := actionservices.DeletePiiMasking(ctx, id)
		if err != nil {
			return false, fmt.Errorf("failed to delete PiiMasking: %v", err)
		}
	case actionservices.ActionTypeErrorSampler:
		err := actionservices.DeleteErrorSampler(ctx, id)
		if err != nil {
			return false, fmt.Errorf("failed to delete ErrorSampler: %v", err)
		}
	case actionservices.ActionTypeLatencySampler:
		err := actionservices.DeleteLatencySampler(ctx, id)
		if err != nil {
			return false, fmt.Errorf("failed to delete LatencySampler: %v", err)
		}
	case actionservices.ActionTypeProbabilisticSampler:
		err := actionservices.DeleteProbabilisticSampler(ctx, id)
		if err != nil {
			return false, fmt.Errorf("failed to delete ProbabilisticSampler: %v", err)
		}
	case actionservices.ActionTypeRenameAttribute:
		err := actionservices.DeleteRenameAttribute(ctx, id)
		if err != nil {
			return false, fmt.Errorf("failed to delete RenameAttribute: %v", err)
		}
	default:
		return false, fmt.Errorf("unsupported action type: %s", actionType)
	}

	// Return true if the deletion was successful
	return true, nil
}

// CreateInstrumentationRule is the resolver for the createInstrumentationRule field.
func (r *mutationResolver) CreateInstrumentationRule(ctx context.Context, instrumentationRule model.InstrumentationRuleInput) (*model.InstrumentationRule, error) {
	// InstrumentationRules feature has been removed
	return nil, fmt.Errorf("InstrumentationRules feature has been removed from the system")
}

// UpdateInstrumentationRule is the resolver for the updateInstrumentationRule field.
func (r *mutationResolver) UpdateInstrumentationRule(ctx context.Context, ruleID string, instrumentationRule model.InstrumentationRuleInput) (*model.InstrumentationRule, error) {
	// InstrumentationRules feature has been removed
	return nil, fmt.Errorf("InstrumentationRules feature has been removed from the system")
}

// DeleteInstrumentationRule is the resolver for the deleteInstrumentationRule field.
func (r *mutationResolver) DeleteInstrumentationRule(ctx context.Context, ruleID string) (bool, error) {
	// InstrumentationRules feature has been removed
	return false, fmt.Errorf("InstrumentationRules feature has been removed from the system")
}

// ComputePlatform is the resolver for the computePlatform field.
func (r *queryResolver) ComputePlatform(ctx context.Context) (*model.ComputePlatform, error) {
	return &model.ComputePlatform{
		ComputePlatformType: model.ComputePlatformTypeK8s,
	}, nil
}

// Config is the resolver for the config field.
func (r *queryResolver) Config(ctx context.Context) (*model.GetConfigResponse, error) {
	response := services.GetConfig(ctx)

	gqlResponse := &model.GetConfigResponse{
		Installation: model.InstallationStatus(response.Installation),
	}

	return gqlResponse, nil
}

// DestinationTypes is the resolver for the destinationTypes field.
func (r *queryResolver) DestinationTypes(ctx context.Context) (*model.GetDestinationTypesResponse, error) {
	destTypes := services.GetDestinationTypes()

	return &destTypes, nil
}

// DestinationTypeDetails is the resolver for the destinationTypeDetails field.
func (r *queryResolver) DestinationTypeDetails(ctx context.Context, typeArg string) (*model.GetDestinationDetailsResponse, error) {
	destType := common.DestinationType(typeArg)
	destTypeConfig, err := services.GetDestinationTypeConfig(destType)
	if err != nil {
		return nil, fmt.Errorf("destination type %s not found", destType)
	}

	var resp model.GetDestinationDetailsResponse
	for _, field := range destTypeConfig.Spec.Fields {
		componentPropsJSON, err := json.Marshal(field.ComponentProps)
		if err != nil {
			return nil, fmt.Errorf("error marshalling component properties: %v", err)
		}

		resp.Fields = append(resp.Fields, &model.Field{
			Name:                field.Name,
			DisplayName:         field.DisplayName,
			ComponentType:       field.ComponentType,
			ComponentProperties: string(componentPropsJSON),
			InitialValue:        &field.InitialValue,
		})

	}

	return &resp, nil
}

// PotentialDestinations is the resolver for the potentialDestinations field.
func (r *queryResolver) PotentialDestinations(ctx context.Context) ([]*model.DestinationDetails, error) {
	potentialDestinations := services.PotentialDestinations(ctx)
	if potentialDestinations == nil {
		return nil, fmt.Errorf("failed to fetch potential destinations")
	}

	// Convert []destination_recognition.DestinationDetails to []*DestinationDetails
	var result []*model.DestinationDetails
	for _, dest := range potentialDestinations {

		fieldsString, err := json.Marshal(dest.Fields)
		if err != nil {
			return nil, fmt.Errorf("error marshalling fields: %v", err)
		}

		result = append(result, &model.DestinationDetails{
			Type:   string(dest.Type),
			Fields: string(fieldsString),
		})
	}

	return result, nil
}

// GetOverviewMetrics is the resolver for the getOverviewMetrics field.
func (r *queryResolver) GetOverviewMetrics(ctx context.Context) (*model.OverviewMetricsResponse, error) {
	if r.MetricsConsumer == nil {
		return nil, fmt.Errorf("metrics consumer not initialized")
	}

	sourcesMetrics := r.MetricsConsumer.GetSourcesMetrics()
	destinationsMetrics := r.MetricsConsumer.GetDestinationsMetrics()

	var sourcesResp []*model.SingleSourceMetricsResponse
	for sID, metric := range sourcesMetrics {
		sourcesResp = append(sourcesResp, &model.SingleSourceMetricsResponse{
			Namespace:     sID.Namespace,
			Kind:          string(sID.Kind),
			Name:          sID.Name,
			TotalDataSent: int(metric.TotalDataSent()),
			Throughput:    int(metric.TotalThroughput()),
		})
	}

	var destinationsResp []*model.SingleDestinationMetricsResponse
	for destId, metric := range destinationsMetrics {
		destinationsResp = append(destinationsResp, &model.SingleDestinationMetricsResponse{
			ID:            destId,
			TotalDataSent: int(metric.TotalDataSent()),
			Throughput:    int(metric.TotalThroughput()),
		})
	}

	return &model.OverviewMetricsResponse{
		Sources:      sourcesResp,
		Destinations: destinationsResp,
	}, nil
}

// DescribeOdigos is the resolver for the describeOdigos field.
func (r *queryResolver) DescribeOdigos(ctx context.Context) (*model.OdigosAnalyze, error) {
	return odigos_describe.GetOdigosDescription(ctx)
}

// DescribeSource is the resolver for the describeSource field.
func (r *queryResolver) DescribeSource(ctx context.Context, namespace string, kind string, name string) (*model.SourceAnalyze, error) {
	return source_describe.GetSourceDescription(ctx, namespace, kind, name)
}

// ComputePlatform returns ComputePlatformResolver implementation.
func (r *Resolver) ComputePlatform() ComputePlatformResolver { return &computePlatformResolver{r} }

// Destination returns DestinationResolver implementation.
func (r *Resolver) Destination() DestinationResolver { return &destinationResolver{r} }

// K8sActualNamespace returns K8sActualNamespaceResolver implementation.
func (r *Resolver) K8sActualNamespace() K8sActualNamespaceResolver {
	return &k8sActualNamespaceResolver{r}
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type computePlatformResolver struct{ *Resolver }
type destinationResolver struct{ *Resolver }
type k8sActualNamespaceResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
