// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package mux

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type bpfMuxRouteMatchT struct {
	Path     [128]int8
	PathLen  uint32
	HasMatch bool
	_        [3]byte
}

type bpfSliceArrayBuff struct{ Buff [1024]uint8 }

type bpfSpanContext struct {
	TraceID    [16]uint8
	SpanID     [8]uint8
	TraceFlags uint8
	Padding    [7]uint8
}

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
	bpfVariableSpecs
}

// bpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	UprobeRouteMatch        *ebpf.ProgramSpec `ebpf:"uprobe_Route_Match"`
	UprobeRouteMatchReturns *ebpf.ProgramSpec `ebpf:"uprobe_Route_Match_Returns"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	AllocMap                 *ebpf.MapSpec `ebpf:"alloc_map"`
	Events                   *ebpf.MapSpec `ebpf:"events"`
	GoContextToSc            *ebpf.MapSpec `ebpf:"go_context_to_sc"`
	InstrumentationConfigMap *ebpf.MapSpec `ebpf:"instrumentation_config_map"`
	MuxRouteMatchMap         *ebpf.MapSpec `ebpf:"mux_route_match_map"`
	ProbeActiveSamplerMap    *ebpf.MapSpec `ebpf:"probe_active_sampler_map"`
	SamplersConfigMap        *ebpf.MapSpec `ebpf:"samplers_config_map"`
	SliceArrayBuffMap        *ebpf.MapSpec `ebpf:"slice_array_buff_map"`
	TrackedSpansBySc         *ebpf.MapSpec `ebpf:"tracked_spans_by_sc"`
}

// bpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfVariableSpecs struct {
	CtxPtrPos               *ebpf.VariableSpec `ebpf:"ctx_ptr_pos"`
	EndAddr                 *ebpf.VariableSpec `ebpf:"end_addr"`
	Hex                     *ebpf.VariableSpec `ebpf:"hex"`
	IsRegistersAbi          *ebpf.VariableSpec `ebpf:"is_registers_abi"`
	RouteRouteconfPos       *ebpf.VariableSpec `ebpf:"route_routeconf_pos"`
	RouteconfRegexpPos      *ebpf.VariableSpec `ebpf:"routeconf_regexp_pos"`
	RoutematchRoutePos      *ebpf.VariableSpec `ebpf:"routematch_route_pos"`
	RouteregexpReversePos   *ebpf.VariableSpec `ebpf:"routeregexp_reverse_pos"`
	RouteregexpTemplatePos  *ebpf.VariableSpec `ebpf:"routeregexp_template_pos"`
	RouteregexpgroupPathPos *ebpf.VariableSpec `ebpf:"routeregexpgroup_path_pos"`
	StartAddr               *ebpf.VariableSpec `ebpf:"start_addr"`
	TotalCpus               *ebpf.VariableSpec `ebpf:"total_cpus"`
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
	bpfVariables
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	AllocMap                 *ebpf.Map `ebpf:"alloc_map"`
	Events                   *ebpf.Map `ebpf:"events"`
	GoContextToSc            *ebpf.Map `ebpf:"go_context_to_sc"`
	InstrumentationConfigMap *ebpf.Map `ebpf:"instrumentation_config_map"`
	MuxRouteMatchMap         *ebpf.Map `ebpf:"mux_route_match_map"`
	ProbeActiveSamplerMap    *ebpf.Map `ebpf:"probe_active_sampler_map"`
	SamplersConfigMap        *ebpf.Map `ebpf:"samplers_config_map"`
	SliceArrayBuffMap        *ebpf.Map `ebpf:"slice_array_buff_map"`
	TrackedSpansBySc         *ebpf.Map `ebpf:"tracked_spans_by_sc"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.AllocMap,
		m.Events,
		m.GoContextToSc,
		m.InstrumentationConfigMap,
		m.MuxRouteMatchMap,
		m.ProbeActiveSamplerMap,
		m.SamplersConfigMap,
		m.SliceArrayBuffMap,
		m.TrackedSpansBySc,
	)
}

// bpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfVariables struct {
	CtxPtrPos               *ebpf.Variable `ebpf:"ctx_ptr_pos"`
	EndAddr                 *ebpf.Variable `ebpf:"end_addr"`
	Hex                     *ebpf.Variable `ebpf:"hex"`
	IsRegistersAbi          *ebpf.Variable `ebpf:"is_registers_abi"`
	RouteRouteconfPos       *ebpf.Variable `ebpf:"route_routeconf_pos"`
	RouteconfRegexpPos      *ebpf.Variable `ebpf:"routeconf_regexp_pos"`
	RoutematchRoutePos      *ebpf.Variable `ebpf:"routematch_route_pos"`
	RouteregexpReversePos   *ebpf.Variable `ebpf:"routeregexp_reverse_pos"`
	RouteregexpTemplatePos  *ebpf.Variable `ebpf:"routeregexp_template_pos"`
	RouteregexpgroupPathPos *ebpf.Variable `ebpf:"routeregexpgroup_path_pos"`
	StartAddr               *ebpf.Variable `ebpf:"start_addr"`
	TotalCpus               *ebpf.Variable `ebpf:"total_cpus"`
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	UprobeRouteMatch        *ebpf.Program `ebpf:"uprobe_Route_Match"`
	UprobeRouteMatchReturns *ebpf.Program `ebpf:"uprobe_Route_Match_Returns"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.UprobeRouteMatch,
		p.UprobeRouteMatchReturns,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_arm64_bpfel.o
var _BpfBytes []byte
