apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: karmatap
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - nodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - daemonsets
      - deployments
      - statefulsets
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - daemonsets/finalizers
      - deployments/finalizers
      - statefulsets/finalizers
    verbs:
      - update
  - apiGroups:
      - apps
    resources:
      - daemonsets/status
      - deployments/status
      - statefulsets/status
    verbs:
      - get
  - apiGroups:
      - codekarma.tech
    resources:
      - collectorsgroups
      - karmainstrumentedapplications
      - destinations
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - codekarma.tech
    resources:
      - collectorsgroups/finalizers
      - karmainstrumentedapplications/finalizers
      - destinations/finalizers
    verbs:
      - update
  - apiGroups:
      - codekarma.tech
    resources:
      - collectorsgroups/status
      - karmainstrumentedapplications/status
      - destinations/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
    - codekarma.tech
    resources:
    - karmainstrumentationconfigs
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - codekarma.tech
    resources:
    - karmainstrumentationrules
    verbs:
    - get
    - list
    - watch
